### ISSUE TITLE
Use of hooks?

### ISSUE THREAD

**Issue by AaronGullickson** [MPIDR/rsocsim#14]
Hello, Berkeley Demography grad here and I am excited to see this project. I have been playing around with it a bit in the hopes of doing a project that looks at the ineritance of group ancestry in populations with varying degrees of exogamy. However, I am finding the set up for how births are assigned back to groups to be limiting. From Carl Mason's documentation of SOCSIM, it seems that users could adjust this with a hook of the `enhance_birth` function in the C code. Is it possible to use these kinds of hooks directly in rsocsim or would I need to fork and do it myself (or use vanilla SOCSIM).

**Comment by tomthe** [comment]
I am sorry for this long delay. I was sure I did answer you back in September, but I must have done something wrong. Do you still consider rsocsim?

I removed all the files related to enhancements, but I did not remove the hooks in the main code.
You have 3 options:
* use vanilla socsim (I wouldn't)
* use rsocsim, fork it and change the birth function directly
* edit in the hooks again (this would also require some changes in rsocsim, so that the hooks get used. But these changes could be integrated into official rsocsim)

I would recommend to fork rsocsim and edit the birth function directly. That would get you the fastest results and as long as you don't edit something else very much, you could still update it with rsocsim updates easily.

**Comment by AaronGullickson** [comment]
Hi @tomthe. I sent you an email a couple of weeks about how we resolved this issue. Basically, we are using R to do some of the simulation - the marriages and group assignment. It took a bit to get set up but works great now. So, no need for this anymore. Thanks for all of your help!
